version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
        
      - run: |
          python3.8 -m venv venv
          source ./venv/bin/activate

          pip install pytest

          pytest test_calculations.py --jnuit-xml=test-results/pytest.xml
      - store_test_results:
          path: test-results